### ISSUE TITLE
New videos on the home page as well as category page are not updating

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#29]

**Comment by ShivaniAjency** [comment]
Description:
When you add a new video it gets displayed on top but The videos that are already added does not get sorted by date.

1) On Live
In the below-given screenshot video published on Mar 27, 2020, is appearing first (marked)

![image](https://user-images.githubusercontent.com/75774252/115503509-271cf200-a294-11eb-9467-655766998274.png)

Also in the trending video section on the homepage, you cannot see the latest video
![image](https://user-images.githubusercontent.com/75774252/115503805-a5799400-a294-11eb-9c8e-e03eb03d51fa.png)

**Comment by ankitasangodkar** [comment]
@ShivaniAjency @EktaNaik 
Here are a few important points:
1. **Trending Videos on Homepage**
--  Every video that has to be displayed on the homepage under this section has to be marked as **Featured Article**

2. Banner Video
--  Video that has to be displayed as the banner on https://www.healthkart.com/connect/video page have to be marked as **Banner Video**

3. Lastest Video
--  Every new video which has been added gets listed under the Latest video section

**Please note**: If any video does not get display/ listed under Trending Articles even if it is marked as **Featured Article** then it is mainly because of the browser cache
