### ISSUE TITLE
Trending articles section on the homepage to be changed from all time maximum views to maximum views of 1 week

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#36]
Description:
The trending articles section on the home page is currently based on "all-time" maximum views. This need to change to maximum views of 1 week.

Expected Behavior:
Trending articles section on the home page should be based on maximum views of 1 week.

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/113249679-bb6ee700-92dc-11eb-90ba-129b4330e2a9.png)

**Comment by chaitanya-ajency** [comment]
Screenshot [Link](https://i.ibb.co/XYNkVkc/screenshot-staging-healthtkart-kinsta-cloud-2021-05-25-20-03-25.png)

**Comment by EktaNaik** [comment]
@chaitanya-ajency  since logic has been applied to display posts based on maximum views of 1 week, currently no post is being shown on live since probably no post was viewed over the last week; hence showing an empty section on the Home page. See screenshot.
![image](https://user-images.githubusercontent.com/44566188/120275342-c808bf00-c2ce-11eb-9036-5489cb102998.png)


Please change the logic as below:
1. Display the 2 posts based on maximum views of 1 week
2. If post count in the section is less than minimum count (i.e. 2 for this section) then display posts with max view count irrespective of last week duration; sorted by publish date.

**Comment by EktaNaik** [comment]
@chaitanya-ajency Logic seems to be working fine now; required number of posts are being displayed sorted by view count. Also, no older post is being displayed here which indicates that the 7days period is being considered while checking for the view count. Let's wait till Monday to re-confirm this (change of order, etc.) and then close the issue accordingly.

**Comment by EktaNaik** [comment]
Fixed.
