### ISSUE TITLE
Editor's pick section to select articles based on the last 15 days of maximum views

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#37]
Description:
Editors pick displays the articles with third most maximum views, fourth-most maximum views.... so on

Expected Behavior:

- Editor's pick section to select articles based on the last 15 days of maximum views.
- The articles in the trending article section should not get displayed again here.

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/113250440-240a9380-92de-11eb-8df6-6e68e68a7ced.png)

**Comment by chaitanya-ajency** [comment]
Editors pic section [screenshot](https://i.ibb.co/p1g8fk0/screenshot-staging-healthtkart-kinsta-cloud-2021-05-25-19-59-44.png)

**Comment by snehaajency** [comment]
![image](https://user-images.githubusercontent.com/4660706/119608724-12dc8f80-be14-11eb-9802-4b576f62d330.png)

**Comment by EktaNaik** [comment]
@chaitanya-ajency since logic has been applied to display posts based on maximum views of last 15days, only 3-4 posts might be shown in this section if less than 6 posts were viewed over the last week; hence showing an incomplete section on the Home page. 

Please change the logic as below:

1. Display the 6 posts based on maximum views of last 15days
2. If post count in the section is less than minimum count (i.e. 6 for this section) then display posts with max view count irrespective of last 15days duration; sorted by publish date.
3. Posts displayed in trending articles section should not be displayed again in this section

**Comment by EktaNaik** [comment]
@chaitanya-ajency Logic seems to be working fine now; required number of posts are being displayed sorted by view count. Also, no older post is being displayed here which indicates that the 15days period is being considered while checking for the view count. Let's wait till Monday to re-confirm this and then close the issue accordingly.

**Comment by EktaNaik** [comment]
Fixed.
